
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/page";
import Navbar from "@/components/Navbar/page";
import MobileNavbar from "@/components/Navbar/MobileNavbar";
import dynamic from "next/dynamic";

const StoreProvider = dynamic(() => import("./StoreProvider"), {
    ssr: false
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "TNP",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider>
                    <MobileNavbar />
                    <Navbar />

                    {children}

                    <Footer />
                </StoreProvider>
            </body>
        </html>
    );
}
